# Generated by Django 5.2.8 on 2026-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/photos/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, null=True, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de service',
                'verbose_name_plural': 'Photos de services',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_service', models.CharField(choices=[('HEBERGEMENT', 'Hébergement'), ('SNACK', 'Snack / Restaurant'), ('ACTIVITE', 'Activité / Loisir'), ('TRANSPORT', 'Transport')], max_length=20, verbose_name='Type de service')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('prix_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix minimum (pour comparateur)')),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix maximum (pour comparateur)')),
                ('adresse', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (géolocalisation)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (géolocalisation)')),
                ('horaire_ouverture', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('horaire_fermeture', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('options_livraison', models.BooleanField(default=False, verbose_name='Livraison disponible')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Service actif')),
                ('est_signale', models.BooleanField(default=False, verbose_name='Signalé pour modération')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
    ]
