# Generated by Django 5.2.8 on 2026-04-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='professionnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.profilprofessionnel', verbose_name='Professionnel'),
        ),
        migrations.AddField(
            model_name='photoservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service', verbose_name='Service'),
        ),
    ]
