# Generated by Django 5.2.8 on 2026-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de ticket',
                'verbose_name_plural': 'Messages de tickets',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('REMBOURSEMENT', 'Demande de remboursement'), ('ANNULATION', "Demande d'annulation"), ('PROBLEME', 'Problème technique'), ('ACCES_COMPTE', 'Accès au compte'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de demande')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
            ],
            options={
                'verbose_name': 'Ticket de support',
                'verbose_name_plural': 'Tickets de support',
                'ordering': ['-date_creation'],
            },
        ),
    ]
