# Generated by Django 5.2.8 on 2026-04-20 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('type_evenement', models.CharField(choices=[('FESTIVAL', 'Festival'), ('CONCERT', 'Concert'), ('SPORTIF', 'Événement sportif'), ('CULTUREL', 'Visite culturelle'), ('GASTRONOMIE', 'Gastronomie'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'événement")),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('lieu', models.CharField(max_length=300, verbose_name='Lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name="Image de l'événement")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Événement actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='users.profilprofessionnel', verbose_name='Organisateur (Professionnel)')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RESERVATION', 'Réservation'), ('PROMOTION', 'Promotion'), ('EVENEMENT', 'Nouvel événement'), ('AVIS', 'Nouvel avis'), ('SYSTEME', 'Système')], max_length=20, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
