# Generated by Django 5.2.8 on 2026-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('FLOOZ', 'Flooz (Moov)'), ('TMONEY', 'T-Money (Togocom)')], max_length=10, verbose_name='Opérateur mobile')),
                ('mode_verification', models.CharField(choices=[('AUTOMATIQUE', 'API automatique (Flooz)'), ('MANUELLE', 'Manuelle (T-Money)')], max_length=15, verbose_name='Mode de vérification')),
                ('numero_telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone utilisé')),
                ('reference_transaction', models.CharField(max_length=100, verbose_name='Référence / code de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'Vérification en cours'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut du paiement')),
                ('capture_ecran', models.ImageField(blank=True, null=True, upload_to='paiements/captures/', verbose_name="Capture d'écran du paiement")),
                ('commentaire_rejet', models.TextField(blank=True, null=True, verbose_name='Raison du rejet (si rejeté)')),
                ('reponse_api', models.JSONField(blank=True, null=True, verbose_name="Réponse brute de l'API Flooz")),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Paiement acompte',
                'verbose_name_plural': 'Paiements acomptes',
            },
        ),
        migrations.CreateModel(
            name='PaiementSolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant solde payé (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('FLOOZ', 'Flooz (Moov)'), ('TMONEY', 'T-Money (Togocom)')], max_length=10, verbose_name='Mode de paiement du solde')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence transaction (si mobile)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement solde',
                'verbose_name_plural': 'Paiements soldes',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reservation', models.CharField(choices=[('HEBERGEMENT', "Réservation d'hébergement"), ('TABLE', 'Réservation de table')], max_length=20, verbose_name='Type de réservation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement acompte'), ('ACOMPTE_EN_VERIFICATION', 'Acompte en vérification'), ('CONFIRMEE', 'Confirmée'), ('SOLDE_EN_ATTENTE', 'En attente du solde'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30, verbose_name='Statut')),
                ('date_debut', models.DateField(verbose_name='Date de début / arrivée')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin / départ (hébergement)')),
                ('heure_reservation', models.TimeField(blank=True, null=True, verbose_name='Heure de réservation (table)')),
                ('nombre_personnes', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message ou demande spéciale')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('type_acompte', models.CharField(choices=[('POURCENTAGE', 'Pourcentage du prix total'), ('MONTANT_FIXE', 'Montant fixe en FCFA')], max_length=20, verbose_name="Type d'acompte")),
                ('valeur_acompte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur acompte (% ou FCFA selon type)')),
                ('montant_acompte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant acompte calculé (FCFA)')),
                ('solde_restant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde restant à payer sur place (FCFA)')),
                ('solde_paye', models.BooleanField(default=False, verbose_name='Solde réglé sur place')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
