# Generated by Django 5.2.8 on 2026-04-20 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementacompte',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (professionnel)'),
        ),
        migrations.AddField(
            model_name='paiementsolde',
            name='confirme_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldes_confirmes', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par (professionnel)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.service', verbose_name='Service réservé'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='touriste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Touriste'),
        ),
        migrations.AddField(
            model_name='paiementsolde',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_solde', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AddField(
            model_name='paiementacompte',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_acompte', to='reservations.reservation', verbose_name='Réservation'),
        ),
    ]
